# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: twopc.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'twopc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btwopc.proto\x12\x05twopc\"=\n\x0bVoteRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x16\n\x0e\x63oordinator_id\x18\x02 \x01(\t\"Y\n\x0cVoteResponse\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x19\n\x04vote\x18\x02 \x01(\x0e\x32\x0b.twopc.Vote\x12\x16\n\x0eparticipant_id\x18\x03 \x01(\t\"\"\n\x0fVoteResponseAck\x12\x0f\n\x07message\x18\x01 \x01(\t\"`\n\x0f\x44\x65\x63isionRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x1d\n\x08\x64\x65\x63ision\x18\x02 \x01(\x0e\x32\x0b.twopc.Vote\x12\x16\n\x0e\x63oordinator_id\x18\x03 \x01(\t\"R\n\x10\x44\x65\x63isionResponse\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x16\n\x0eparticipant_id\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\"&\n\x13\x44\x65\x63isionResponseAck\x12\x0f\n\x07message\x18\x01 \x01(\t\"E\n\x13\x44\x65\x63isionVoteRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x16\n\x0eparticipant_id\x18\x02 \x01(\t**\n\x04Vote\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06\x43OMMIT\x10\x01\x12\t\n\x05\x41\x42ORT\x10\x02\x32\x85\x01\n\rVotingService\x12/\n\x04Vote\x12\x12.twopc.VoteRequest\x1a\x13.twopc.VoteResponse\x12\x43\n\rApplyDecision\x12\x16.twopc.DecisionRequest\x1a\x1a.twopc.DecisionResponseAck2\xcc\x01\n\x0f\x44\x65\x63isionService\x12\x41\n\x0eGlobalDecision\x12\x16.twopc.DecisionRequest\x1a\x17.twopc.DecisionResponse\x12:\n\x0bReceiveVote\x12\x13.twopc.VoteResponse\x1a\x16.twopc.VoteResponseAck\x12:\n\x07GetVote\x12\x1a.twopc.DecisionVoteRequest\x1a\x13.twopc.VoteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'twopc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VOTE']._serialized_start=505
  _globals['_VOTE']._serialized_end=547
  _globals['_VOTEREQUEST']._serialized_start=22
  _globals['_VOTEREQUEST']._serialized_end=83
  _globals['_VOTERESPONSE']._serialized_start=85
  _globals['_VOTERESPONSE']._serialized_end=174
  _globals['_VOTERESPONSEACK']._serialized_start=176
  _globals['_VOTERESPONSEACK']._serialized_end=210
  _globals['_DECISIONREQUEST']._serialized_start=212
  _globals['_DECISIONREQUEST']._serialized_end=308
  _globals['_DECISIONRESPONSE']._serialized_start=310
  _globals['_DECISIONRESPONSE']._serialized_end=392
  _globals['_DECISIONRESPONSEACK']._serialized_start=394
  _globals['_DECISIONRESPONSEACK']._serialized_end=432
  _globals['_DECISIONVOTEREQUEST']._serialized_start=434
  _globals['_DECISIONVOTEREQUEST']._serialized_end=503
  _globals['_VOTINGSERVICE']._serialized_start=550
  _globals['_VOTINGSERVICE']._serialized_end=683
  _globals['_DECISIONSERVICE']._serialized_start=686
  _globals['_DECISIONSERVICE']._serialized_end=890
# @@protoc_insertion_point(module_scope)
