# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import twopc_pb2 as twopc__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in twopc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VotingServiceStub(object):
    """----- Services -----

    The VotingService is implemented in Python (voting phase) and exposes:
    1. Vote – external RPC used by the coordinator to send vote requests.
    2. ApplyDecision – internal RPC called by the local Node decision process.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Vote = channel.unary_unary(
                '/twopc.VotingService/Vote',
                request_serializer=twopc__pb2.VoteRequest.SerializeToString,
                response_deserializer=twopc__pb2.VoteResponse.FromString,
                _registered_method=True)
        self.ApplyDecision = channel.unary_unary(
                '/twopc.VotingService/ApplyDecision',
                request_serializer=twopc__pb2.DecisionRequest.SerializeToString,
                response_deserializer=twopc__pb2.DecisionResponseAck.FromString,
                _registered_method=True)


class VotingServiceServicer(object):
    """----- Services -----

    The VotingService is implemented in Python (voting phase) and exposes:
    1. Vote – external RPC used by the coordinator to send vote requests.
    2. ApplyDecision – internal RPC called by the local Node decision process.
    """

    def Vote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyDecision(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VotingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Vote': grpc.unary_unary_rpc_method_handler(
                    servicer.Vote,
                    request_deserializer=twopc__pb2.VoteRequest.FromString,
                    response_serializer=twopc__pb2.VoteResponse.SerializeToString,
            ),
            'ApplyDecision': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyDecision,
                    request_deserializer=twopc__pb2.DecisionRequest.FromString,
                    response_serializer=twopc__pb2.DecisionResponseAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'twopc.VotingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('twopc.VotingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VotingService(object):
    """----- Services -----

    The VotingService is implemented in Python (voting phase) and exposes:
    1. Vote – external RPC used by the coordinator to send vote requests.
    2. ApplyDecision – internal RPC called by the local Node decision process.
    """

    @staticmethod
    def Vote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/twopc.VotingService/Vote',
            twopc__pb2.VoteRequest.SerializeToString,
            twopc__pb2.VoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApplyDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/twopc.VotingService/ApplyDecision',
            twopc__pb2.DecisionRequest.SerializeToString,
            twopc__pb2.DecisionResponseAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DecisionServiceStub(object):
    """The DecisionService is implemented in Node.js (decision phase) and exposes:
    1. GlobalDecision – external RPC used by the coordinator to deliver the final decision.
    2. ReceiveVote – internal RPC used by the local Python voting phase to forward its vote.
    3. GetVote – used by the coordinator decision process to collect the stored vote.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GlobalDecision = channel.unary_unary(
                '/twopc.DecisionService/GlobalDecision',
                request_serializer=twopc__pb2.DecisionRequest.SerializeToString,
                response_deserializer=twopc__pb2.DecisionResponse.FromString,
                _registered_method=True)
        self.ReceiveVote = channel.unary_unary(
                '/twopc.DecisionService/ReceiveVote',
                request_serializer=twopc__pb2.VoteResponse.SerializeToString,
                response_deserializer=twopc__pb2.VoteResponseAck.FromString,
                _registered_method=True)
        self.GetVote = channel.unary_unary(
                '/twopc.DecisionService/GetVote',
                request_serializer=twopc__pb2.DecisionVoteRequest.SerializeToString,
                response_deserializer=twopc__pb2.VoteResponse.FromString,
                _registered_method=True)


class DecisionServiceServicer(object):
    """The DecisionService is implemented in Node.js (decision phase) and exposes:
    1. GlobalDecision – external RPC used by the coordinator to deliver the final decision.
    2. ReceiveVote – internal RPC used by the local Python voting phase to forward its vote.
    3. GetVote – used by the coordinator decision process to collect the stored vote.
    """

    def GlobalDecision(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveVote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DecisionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GlobalDecision': grpc.unary_unary_rpc_method_handler(
                    servicer.GlobalDecision,
                    request_deserializer=twopc__pb2.DecisionRequest.FromString,
                    response_serializer=twopc__pb2.DecisionResponse.SerializeToString,
            ),
            'ReceiveVote': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveVote,
                    request_deserializer=twopc__pb2.VoteResponse.FromString,
                    response_serializer=twopc__pb2.VoteResponseAck.SerializeToString,
            ),
            'GetVote': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVote,
                    request_deserializer=twopc__pb2.DecisionVoteRequest.FromString,
                    response_serializer=twopc__pb2.VoteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'twopc.DecisionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('twopc.DecisionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DecisionService(object):
    """The DecisionService is implemented in Node.js (decision phase) and exposes:
    1. GlobalDecision – external RPC used by the coordinator to deliver the final decision.
    2. ReceiveVote – internal RPC used by the local Python voting phase to forward its vote.
    3. GetVote – used by the coordinator decision process to collect the stored vote.
    """

    @staticmethod
    def GlobalDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/twopc.DecisionService/GlobalDecision',
            twopc__pb2.DecisionRequest.SerializeToString,
            twopc__pb2.DecisionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReceiveVote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/twopc.DecisionService/ReceiveVote',
            twopc__pb2.VoteResponse.SerializeToString,
            twopc__pb2.VoteResponseAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/twopc.DecisionService/GetVote',
            twopc__pb2.DecisionVoteRequest.SerializeToString,
            twopc__pb2.VoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
