# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raft.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'raft.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\x04raft\"1\n\x0bVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0c\x63\x61ndidate_id\x18\x02 \x01(\x05\"2\n\x0cVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0cvote_granted\x18\x02 \x01(\x08\":\n\x08LogEntry\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\r\n\x05index\x18\x02 \x01(\x05\x12\x11\n\toperation\x18\x03 \x01(\t\"h\n\rAppendRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x11\n\tleader_id\x18\x02 \x01(\x05\x12\x1f\n\x07\x65ntries\x18\x03 \x03(\x0b\x32\x0e.raft.LogEntry\x12\x15\n\rleader_commit\x18\x04 \x01(\x05\"/\n\x0e\x41ppendResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\"\"\n\rClientRequest\x12\x11\n\toperation\x18\x01 \x01(\t\"2\n\x0e\x43lientResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xb8\x01\n\x04Raft\x12\x34\n\x0bRequestVote\x12\x11.raft.VoteRequest\x1a\x12.raft.VoteResponse\x12:\n\rAppendEntries\x12\x13.raft.AppendRequest\x1a\x14.raft.AppendResponse\x12>\n\x11SendClientRequest\x12\x13.raft.ClientRequest\x1a\x14.raft.ClientResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VOTEREQUEST']._serialized_start=20
  _globals['_VOTEREQUEST']._serialized_end=69
  _globals['_VOTERESPONSE']._serialized_start=71
  _globals['_VOTERESPONSE']._serialized_end=121
  _globals['_LOGENTRY']._serialized_start=123
  _globals['_LOGENTRY']._serialized_end=181
  _globals['_APPENDREQUEST']._serialized_start=183
  _globals['_APPENDREQUEST']._serialized_end=287
  _globals['_APPENDRESPONSE']._serialized_start=289
  _globals['_APPENDRESPONSE']._serialized_end=336
  _globals['_CLIENTREQUEST']._serialized_start=338
  _globals['_CLIENTREQUEST']._serialized_end=372
  _globals['_CLIENTRESPONSE']._serialized_start=374
  _globals['_CLIENTRESPONSE']._serialized_end=424
  _globals['_RAFT']._serialized_start=427
  _globals['_RAFT']._serialized_end=611
# @@protoc_insertion_point(module_scope)
